# Generated by Django 5.0.6 on 2024-09-08 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_student_purchased_products_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='availablehour',
            table=None,
        ),
        migrations.AlterModelTable(
            name='course',
            table=None,
        ),
        migrations.AlterModelTable(
            name='coursesession',
            table=None,
        ),
        migrations.AlterModelTable(
            name='enrollment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='groupsession',
            table=None,
        ),
        migrations.AlterModelTable(
            name='livestream',
            table=None,
        ),
        migrations.AlterModelTable(
            name='payment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
        migrations.AlterModelTable(
            name='productpurchase',
            table=None,
        ),
        migrations.AlterModelTable(
            name='review',
            table=None,
        ),
        migrations.AlterModelTable(
            name='session',
            table=None,
        ),
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
