# Generated by Django 5.0.6 on 2024-08-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='purchased_products',
            field=models.ManyToManyField(related_name='students', through='core.ProductPurchase', to='core.product'),
        ),
    ]
