# Generated by Django 5.0.6 on 2024-07-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablehour',
            name='is_recurring',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
