# Generated by Django 5.0.6 on 2024-09-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='purchased_products',
            field=models.ManyToManyField(related_name='students', through='core.ProductPurchase', to='core.product'),
        ),
        migrations.AlterModelTable(
            name='availablehour',
            table='app3_availablehour',
        ),
        migrations.AlterModelTable(
            name='course',
            table='app3_course',
        ),
        migrations.AlterModelTable(
            name='coursesession',
            table='app3_coursesession',
        ),
        migrations.AlterModelTable(
            name='enrollment',
            table='app3_enrollment',
        ),
        migrations.AlterModelTable(
            name='groupsession',
            table='app3_groupsession',
        ),
        migrations.AlterModelTable(
            name='livestream',
            table='app3_livestream',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='app3_payment',
        ),
        migrations.AlterModelTable(
            name='product',
            table='app3_product',
        ),
        migrations.AlterModelTable(
            name='productpurchase',
            table='app3_productpurchase',
        ),
        migrations.AlterModelTable(
            name='review',
            table='app3_review',
        ),
        migrations.AlterModelTable(
            name='session',
            table='app3_session',
        ),
        migrations.AlterModelTable(
            name='student',
            table='app3_student',
        ),
    ]
