# Generated by Django 5.0.6 on 2024-07-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_availablehour_is_recurring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='booked_hours',
            field=models.ManyToManyField(blank=True, related_name='students', to='core.availablehour'),
        ),
    ]
