# Generated by Django 5.0.6 on 2024-07-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_course_capacity_alter_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='event_type',
            field=models.CharField(choices=[('1-to-1', 'One-to-One Session'), ('group', 'Group Session'), ('live', 'Live Stream'), ('testing', 'Testing Session')], default='1-to-1', max_length=20),
        ),
    ]
