# Generated by Django 5.0.6 on 2024-07-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_availablehour'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='available_slots',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
