# Generated by Django 5.0.6 on 2024-07-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_session_available_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablehour',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
