# Generated by Django 5.0.6 on 2024-07-18 00:25

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_availablehour_booked_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='date',
            new_name='end_time',
        ),
        migrations.RemoveField(
            model_name='coursesession',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='session',
            name='available_slots',
        ),
        migrations.RemoveField(
            model_name='session',
            name='description',
        ),
        migrations.RemoveField(
            model_name='session',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='session',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='session',
            name='student',
        ),
        migrations.AddField(
            model_name='coursesession',
            name='meeting_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='participants',
            field=models.ManyToManyField(to='core.student'),
        ),
        migrations.AddField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
        ),
    ]
