# Generated by Django 5.0.6 on 2024-07-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_enrollment_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupsession',
            name='cost',
        ),
        migrations.AddField(
            model_name='groupsession',
            name='meeting_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
