# Generated by Django 5.0.6 on 2024-07-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_groupsession_cost_groupsession_meeting_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablehour',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
