# Generated by Django 5.0.6 on 2024-07-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_availablehour_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='booked_hours',
            field=models.ManyToManyField(blank=True, to='core.availablehour'),
        ),
        migrations.AddField(
            model_name='student',
            name='enrolled_courses',
            field=models.ManyToManyField(related_name='students', through='core.Enrollment', to='core.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='purchased_products',
            field=models.ManyToManyField(blank=True, to='core.product'),
        ),
    ]
